In [1]:
import pandas as pd

In [2]:
df_data = pd.DataFrame(pd.read_csv("Data/export-nes-2021-04-15_04-11-11.csv"))

In [3]:
df_data

,code,economy,year,Financing for entrepreneurs,Governmental support and policies,Taxes and bureaucracy,Governmental programs,Basic school entrepreneurial education and training,Post school entrepreneurial education and training,R&D transfer,Commercial and professional infrastructure,Internal market dynamics,Internal market openness,Physical and services infrastructure,Cultural and social norms
0,374,Armenia,2019,2.48,2.69,3.19,2.42,2.06,2.37,2.16,3.35,3.12,2.76,3.91,3.55
1,61,Australia,2019,3.10,2.62,2.70,2.82,2.43,2.81,2.52,3.09,2.70,2.88,3.53,3.15
2,375,Belarus,2019,2.21,2.28,2.73,2.12,2.00,2.86,2.30,3.10,3.28,2.67,4.08,2.39
3,55,Brazil,2019,2.93,2.50,1.87,2.56,1.78,2.67,2.25,2.82,3.44,2.49,3.23,2.47
4,359,Bulgaria,2019,2.75,1.89,2.80,2.07,1.95,2.53,2.17,3.03,3.10,2.68,4.09,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,82,South Korea,2000,2.91,2.63,2.56,2.60,1.98,2.59,2.40,3.71,2.51,3.47,2.67,NaN
918,34,Spain,2000,3.03,2.81,2.38,2.64,2.41,2.59,3.25,2.49,2.56,3.64,2.59,NaN
919,46,Sweden,2000,3.81,2.63,1.85,3.07,2.39,2.93,3.60,3.41,3.19,3.61,2.27,NaN
920,44,United Kingdom,2000,3.29,3.18,3.19,3.11,2.21,2.88,3.73,2.79,3.34,3.94,2.93,NaN
921,1,United States,2000,3.80,3.03,3.12,3.06,2.84,3.15,3.83,3.29,3.33,4.15,3.45,NaN

In [4]:
df_data.isna()

,code,economy,year,Financing for entrepreneurs,Governmental support and policies,Taxes and bureaucracy,Governmental programs,Basic school entrepreneurial education and training,Post school entrepreneurial education and training,R&D transfer,Commercial and professional infrastructure,Internal market dynamics,Internal market openness,Physical and services infrastructure,Cultural and social norms
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
918,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
919,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
920,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
921,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [5]:
df_data.isnull().values.any()

True

In [6]:
df_data.isnull().sum()

code                                                    0
economy                                                 0
year                                                    0
Financing for entrepreneurs                             1
Governmental support and policies                       1
Taxes and bureaucracy                                   1
Governmental programs                                   1
Basic school entrepreneurial education and training     1
Post school entrepreneurial education and training     27
R&D transfer                                            1
Commercial and professional infrastructure              1
Internal market dynamics                                1
Internal market openness                                1
Physical and services infrastructure                    1
Cultural and social norms                              23
dtype: int64

In [7]:
df_data

,code,economy,year,Financing for entrepreneurs,Governmental support and policies,Taxes and bureaucracy,Governmental programs,Basic school entrepreneurial education and training,Post school entrepreneurial education and training,R&D transfer,Commercial and professional infrastructure,Internal market dynamics,Internal market openness,Physical and services infrastructure,Cultural and social norms
0,374,Armenia,2019,2.48,2.69,3.19,2.42,2.06,2.37,2.16,3.35,3.12,2.76,3.91,3.55
1,61,Australia,2019,3.10,2.62,2.70,2.82,2.43,2.81,2.52,3.09,2.70,2.88,3.53,3.15
2,375,Belarus,2019,2.21,2.28,2.73,2.12,2.00,2.86,2.30,3.10,3.28,2.67,4.08,2.39
3,55,Brazil,2019,2.93,2.50,1.87,2.56,1.78,2.67,2.25,2.82,3.44,2.49,3.23,2.47
4,359,Bulgaria,2019,2.75,1.89,2.80,2.07,1.95,2.53,2.17,3.03,3.10,2.68,4.09,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,82,South Korea,2000,2.91,2.63,2.56,2.60,1.98,2.59,2.40,3.71,2.51,3.47,2.67,NaN
918,34,Spain,2000,3.03,2.81,2.38,2.64,2.41,2.59,3.25,2.49,2.56,3.64,2.59,NaN
919,46,Sweden,2000,3.81,2.63,1.85,3.07,2.39,2.93,3.60,3.41,3.19,3.61,2.27,NaN
920,44,United Kingdom,2000,3.29,3.18,3.19,3.11,2.21,2.88,3.73,2.79,3.34,3.94,2.93,NaN
921,1,United States,2000,3.80,3.03,3.12,3.06,2.84,3.15,3.83,3.29,3.33,4.15,3.45,NaN

In [8]:
df_data.dtypes

code                                                     int64
economy                                                 object
year                                                     int64
Financing for entrepreneurs                            float64
Governmental support and policies                      float64
Taxes and bureaucracy                                  float64
Governmental programs                                  float64
Basic school entrepreneurial education and training    float64
Post school entrepreneurial education and training     float64
R&D transfer                                           float64
Commercial and professional infrastructure             float64
Internal market dynamics                               float64
Internal market openness                               float64
Physical and services infrastructure                   float64
Cultural and social norms                              float64
dtype: object

In [9]:
df_data = df_data.set_index(["code"])
df_data

,economy,year,Financing for entrepreneurs,Governmental support and policies,Taxes and bureaucracy,Governmental programs,Basic school entrepreneurial education and training,Post school entrepreneurial education and training,R&D transfer,Commercial and professional infrastructure,Internal market dynamics,Internal market openness,Physical and services infrastructure,Cultural and social norms
code,,,,,,,,,,,,,,
374,Armenia,2019,2.48,2.69,3.19,2.42,2.06,2.37,2.16,3.35,3.12,2.76,3.91,3.55
61,Australia,2019,3.10,2.62,2.70,2.82,2.43,2.81,2.52,3.09,2.70,2.88,3.53,3.15
375,Belarus,2019,2.21,2.28,2.73,2.12,2.00,2.86,2.30,3.10,3.28,2.67,4.08,2.39
55,Brazil,2019,2.93,2.50,1.87,2.56,1.78,2.67,2.25,2.82,3.44,2.49,3.23,2.47
359,Bulgaria,2019,2.75,1.89,2.80,2.07,1.95,2.53,2.17,3.03,3.10,2.68,4.09,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,South Korea,2000,2.91,2.63,2.56,2.60,1.98,2.59,2.40,3.71,2.51,3.47,2.67,NaN
34,Spain,2000,3.03,2.81,2.38,2.64,2.41,2.59,3.25,2.49,2.56,3.64,2.59,NaN
46,Sweden,2000,3.81,2.63,1.85,3.07,2.39,2.93,3.60,3.41,3.19,3.61,2.27,NaN
44,United Kingdom,2000,3.29,3.18,3.19,3.11,2.21,2.88,3.73,2.79,3.34,3.94,2.93,NaN
1,United States,2000,3.80,3.03,3.12,3.06,2.84,3.15,3.83,3.29,3.33,4.15,3.45,NaN

In [10]:
df_data = df_data.dropna()

In [11]:
df_data.columns = df_data.columns.str.replace(' ','_')
df_data

,economy,year,Financing_for_entrepreneurs,Governmental_support_and_policies,Taxes_and_bureaucracy,Governmental_programs,Basic_school_entrepreneurial_education_and_training,Post_school_entrepreneurial_education_and_training,R&D_transfer,Commercial_and_professional_infrastructure,Internal_market_dynamics,Internal_market_openness,Physical_and_services_infrastructure,Cultural_and_social_norms
code,,,,,,,,,,,,,,
374,Armenia,2019,2.48,2.69,3.19,2.42,2.06,2.37,2.16,3.35,3.12,2.76,3.91,3.55
61,Australia,2019,3.10,2.62,2.70,2.82,2.43,2.81,2.52,3.09,2.70,2.88,3.53,3.15
375,Belarus,2019,2.21,2.28,2.73,2.12,2.00,2.86,2.30,3.10,3.28,2.67,4.08,2.39
55,Brazil,2019,2.93,2.50,1.87,2.56,1.78,2.67,2.25,2.82,3.44,2.49,3.23,2.47
359,Bulgaria,2019,2.75,1.89,2.80,2.07,1.95,2.53,2.17,3.03,3.10,2.68,4.09,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,Switzerland,2002,3.03,2.46,2.84,2.72,1.78,3.21,2.77,3.29,2.59,2.70,4.45,2.57
886,Taiwan,2002,3.49,3.15,2.81,3.27,2.02,2.95,3.40,3.53,4.09,3.08,4.27,4.08
66,Thailand,2002,2.77,2.77,2.55,2.31,1.84,2.48,2.00,2.63,3.78,2.22,3.80,2.98
44,United Kingdom,2002,2.93,3.08,2.58,2.60,2.05,2.61,2.12,3.15,2.46,3.04,3.73,2.65
1,United States,2002,4.10,2.92,3.17,2.99,2.66,3.89,3.08,4.06,2.83,3.21,4.52,4.52

In [12]:
df_data = df_data.rename(columns=
                         {"economy":"country"})
df_data

,country,year,Financing_for_entrepreneurs,Governmental_support_and_policies,Taxes_and_bureaucracy,Governmental_programs,Basic_school_entrepreneurial_education_and_training,Post_school_entrepreneurial_education_and_training,R&D_transfer,Commercial_and_professional_infrastructure,Internal_market_dynamics,Internal_market_openness,Physical_and_services_infrastructure,Cultural_and_social_norms
code,,,,,,,,,,,,,,
374,Armenia,2019,2.48,2.69,3.19,2.42,2.06,2.37,2.16,3.35,3.12,2.76,3.91,3.55
61,Australia,2019,3.10,2.62,2.70,2.82,2.43,2.81,2.52,3.09,2.70,2.88,3.53,3.15
375,Belarus,2019,2.21,2.28,2.73,2.12,2.00,2.86,2.30,3.10,3.28,2.67,4.08,2.39
55,Brazil,2019,2.93,2.50,1.87,2.56,1.78,2.67,2.25,2.82,3.44,2.49,3.23,2.47
359,Bulgaria,2019,2.75,1.89,2.80,2.07,1.95,2.53,2.17,3.03,3.10,2.68,4.09,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,Switzerland,2002,3.03,2.46,2.84,2.72,1.78,3.21,2.77,3.29,2.59,2.70,4.45,2.57
886,Taiwan,2002,3.49,3.15,2.81,3.27,2.02,2.95,3.40,3.53,4.09,3.08,4.27,4.08
66,Thailand,2002,2.77,2.77,2.55,2.31,1.84,2.48,2.00,2.63,3.78,2.22,3.80,2.98
44,United Kingdom,2002,2.93,3.08,2.58,2.60,2.05,2.61,2.12,3.15,2.46,3.04,3.73,2.65
1,United States,2002,4.10,2.92,3.17,2.99,2.66,3.89,3.08,4.06,2.83,3.21,4.52,4.52

In [14]:
from sqlalchemy import create_engine
import pandas as pd
from db_conn import user_name
from db_conn import password
import psycopg2

conn = psycopg2.connect(
   database="postgres", user=f'{user_name}', password=f'{password}', host='127.0.0.1', port= '5432'
)

conn.autocommit = True

cursor = conn.cursor()

cursor.execute("SELECT datname FROM pg_database;")

list_database = cursor.fetchall()

dbname = "gem_db"

try:

    if (dbname,) not in list_database:

        cur = conn.cursor()
        cur.execute('CREATE DATABASE ' + dbname)

        cur.close()
        conn.close()

        print("Creating Database...")

        engine = create_engine(f'postgresql://{user_name}:{password}@localhost:5432/{dbname}')

        connection = engine.connect()

        print('-'*30)
        print("Creating Tables, Please wait...")
        print('-'*30)

        df_data.to_sql("framework_conditions", engine)
    #         zhvi_complete_df.to_sql('sales',engine)
        print("Table framework_conditions created successfully")

        connection.close()

        print('-'*30)
        print("Database is ready to use.")
    else:
        print("Database is already exists.")
except:
    print("Something went wrong.")

Creating Database...
------------------------------
Creating Tables, Please wait...
------------------------------
Table framework_conditions created successfully
------------------------------
Database is ready to use.